# Generated by Django 2.2.1 on 2019-10-25 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_to_cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete='', related_name='vendor', to='myapp.Food')),
            ],
        ),
    ]
