# Generated by Django 2.2.1 on 2019-10-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_add_to_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_to_cart',
            old_name='user',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='vendor',
            field=models.ForeignKey(on_delete='', related_name='vendors', to='myapp.Food'),
        ),
    ]
