# Generated by Django 2.2.1 on 2019-10-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191025_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=25)),
                ('vendor', models.CharField(max_length=25)),
                ('food_name', models.CharField(max_length=25)),
                ('food_rate', models.CharField(max_length=25)),
                ('food_type', models.CharField(max_length=25)),
                ('order_status', models.CharField(max_length=25)),
            ],
        ),
    ]
