# Generated by Django 2.2.1 on 2019-10-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date_field',
            field=models.DateField(auto_now=True),
        ),
    ]
